### ISSUE TITLE
Server Listing and Leaving

### ISSUE THREAD

**Issue by vectorvitale** [serebit/autotitan#1]
Similar to the **Red-Discordbot**, add a command which allows you to view what servers the bot is connected to (in a pretty markdown format) and then add the ability to force the bot to leave a server.

**Comment by serebit** [comment]
This was on the mental list of things to do already. Can't wait to close this issue.

**Comment by serebit** [comment]
Server leaving was added in [c5e141b](https://github.com/serebit/autotitan/commit/c5e141b1c5f3880fbd878828447e462d5cff060b). Server listing will be added soon.

**Comment by serebit** [comment]
Added server listing in [d7620b6](https://github.com/serebit/autotitan/commit/d7620b6b2fe00a6cc8e24d61394a7d427816b9cf). Closing issue.
